#include "song_happy_birthday.h"

#define SONG_DEFAULT_FINGER_BITMASK 0x01U
#define SONG_PRESS_DURATION_MS 250U
#define SONG_NOTE_DURATION_SHORT_MS 500U
#define SONG_NOTE_DURATION_LONG_MS 1000U

#define SONG_NOTE_EVENT(note_position, duration_ms) \
    { \
        .targetPosition = (note_position), \
        .fingerBitmask = SONG_DEFAULT_FINGER_BITMASK, \
        .pressDuration = SONG_PRESS_DURATION_MS, \
        .noteDuration = (duration_ms) \
    }

static song_state_t happy_birthday_c_major_states[] = {
    /* Happy birthday to you */
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_A4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_C5, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_B4, SONG_NOTE_DURATION_LONG_MS),

    /* Happy birthday to you */
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_A4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_D5, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_C5, SONG_NOTE_DURATION_LONG_MS),

    /* Happy birthday dear [name] */
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_G4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_E4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_C5, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_B4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_A4, SONG_NOTE_DURATION_LONG_MS),

    /* Happy birthday to you */
    SONG_NOTE_EVENT(SONG_NOTE_POS_F4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_F4, SONG_NOTE_DURATION_SHORT_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_E4, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_C5, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_D5, SONG_NOTE_DURATION_LONG_MS),
    SONG_NOTE_EVENT(SONG_NOTE_POS_C5, SONG_NOTE_DURATION_LONG_MS)
};

song_t happy_birthday_c_major_song = {
    .states = happy_birthday_c_major_states,
    .num_states = sizeof(happy_birthday_c_major_states) / sizeof(happy_birthday_c_major_states[0]),
    .count = 0U
};
